DATA_DIRECTORY = "data"
DATA_FILE = f"{DATA_DIRECTORY}/data.csv"
REVENUE_FILE = f"{DATA_DIRECTORY}/revenue.csv"
USD_TWD_FILE = f"{DATA_DIRECTORY}/usd_twd.csv"
TICKER_FILE = "pull-tickers.txt"
EXPORT_FILE = "data_analysis.csv"

URL_DIRECTORY = "urls"
TSMC_URLS = f"{URL_DIRECTORY}/tsmc_urls.csv"
SMIC_URLS = f"{URL_DIRECTORY}/smic_urls.csv"
UMC_URLS = f"{URL_DIRECTORY}/umc_urls.csv"
GF_URLS = f"{URL_DIRECTORY}/gf_urls.csv"
